# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.9'
    addToPath: true
    architecture: 'x64'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cd $(System.DefaultWorkingDirectory)
      ls
      python -m pip install --upgrade pip
      pip install -r requirements.txt --target=".python_packages/lib/site-packages"
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: AzureFunctionApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(6a402904-4a0a-442e-bdfd-ef5aed4feaf8)'
    appType: 'functionAppLinux'
    appName: 'BFYOC-CreateRatings'
    package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'